config/routes.rb
Travlr::Application.routes.draw do

  resources :recommenders, only: [:create, :update, :destroy]
  resources :messages

  root 'home#welcome'
  get "prefs" => 'user_prefs#index'
  get "home/welcome" => 'home#welcome', as: :welcome
  get "home/login" => 'home#login', as: :login
  get "home/logout" => 'home#logout', as: :logout
  post "home/login" => 'home#authenticate', as: :authenticate  
  get 'inbox' => 'inbox#index', as: :inbox
  get 'recommend' => 'recommenders#recommend', as: :recommendation

  resources :users, except: :index
  resources :posts
  

  

end

app/models/message.rb
class Message < ActiveRecord::Base
	validates :subject, presence: true
	validates :body, presence: true
	validates :receiver_username, presence: true

	belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :destroy]
  before_action :authenticate

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message.read = true
    @message.save
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # POST /messages
  # POST /messages.json
  def create
    info = message_params
    @message = Message.new( )
    @message.subject = info[:subject]
    @message.body = info[:body]
    @message.sender_id = session[:user_id]
    @message.receiver_username = info[:receiver_username]
    recipient = User.find_by user_name: info[:receiver_username]
    @message.receiver_id = recipient.id
    @message.read = false;

    respond_to do |format|
      if @message.save
        format.html { redirect_to inbox_path }
        format.json { render action: 'show', status: :created, location: @message }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to inbox_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:subject, :body, :receiver_username, :user_name)
    end

    def authenticate
      unless session[:user_id]
        flash[:notice] = "You must be logged in to view this page"
        redirect_to login_path
      end
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_newmessage.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if params[:user_name] %>
      Username: <%= f.text_field :receiver_username, :value => params[:user_name] %>
    <% else %>
      Username: <%= f.text_field :receiver_username %>
    <%end%>

  </div>
  <div class="field">
    Subject: <%= f.text_field :subject %>
  </div>
  <div class="field">
    Body: <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'newmessage' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= User.find(@message.sender_id).user_name %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @message.receiver_username %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<%= link_to 'Back', inbox_path, class: "btn btn-success" %>  
<%= link_to 'Reply', new_message_path(user_name: User.find(@message.sender_id).user_name), class: "btn btn-danger" %>  