config/routes.rb
Travlr::Application.routes.draw do

  resources :recommenders, only: [:create, :update, :destroy]
  resources :messages

  root 'home#welcome'
  get "prefs" => 'user_prefs#index'
  get "home/welcome" => 'home#welcome', as: :welcome
  get "home/login" => 'home#login', as: :login
  get "home/logout" => 'home#logout', as: :logout
  post "home/login" => 'home#authenticate', as: :authenticate  
  get 'inbox' => 'inbox#index', as: :inbox
  get 'recommend' => 'recommenders#recommend', as: :recommendation

  resources :users, except: :index
  resources :posts
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
	validates :user_name, presence: true, uniqueness: true
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :age, presence: true
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, length: {minimum: 4, maximum: 20}

	has_many :posts
	has_many :messages
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authenticate, only: [:index, :show, :edit, :update]

  # GET /users/1
  # GET /users/1.json
  def show
#    @sent_messages = Message.find_by sender_id: session[:user_id]
    @messages = Message.where(receiver_id: session[:user_id])
    @posts = Post.where(user_id: session[:user_id])
  end 

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id

        Notifier.send_signup_email(@user).deliver
        format.html { redirect_to posts_path, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :first_name, :last_name, :age, :email, :password)
    end

    def authenticate
      unless session[:user_id]
        flash[:notice] = "You must be logged in to view this page"
        redirect_to login_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_newuser.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    First Name: <%= f.text_field :first_name %>
  </div>
  <div class="field">
    Last Name: <%= f.text_field :last_name %>
  </div>
  <div class="field">
    Age: <%= f.number_field :age %>
  </div>
  <div class="field">
    Email: <%= f.email_field :email %>
  </div>
  <div class="field">
    Username: <%= f.text_field :user_name %>
  </div>
  <div class="field">
    Password (Must be 4-20 characters long): <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'newuser' %>

<%= link_to 'Back', user_path(@user) %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render 'newuser' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center"> <%= @user.first_name %> <%= @user.last_name %></h1>

<div class="row">
	<h3 class="col-md-4 text-center"> Username </h3>
	<h3 class="col-md-4 text-center"> Age </h3>
	<h3 class="col-md-4 text-center"> Email </h3>
</div>

<div class="row padded-small">
	<div class="col-md-4 text-center"> <%= @user.user_name %> </div>
	<div class="col-md-4 text-center"> <%= @user.age %> </div>
	<div class="col-md-4 text-center"> <%= @user.email %> </div>
</div>

<% if session[:user_id] == @user.id %>
	<div class="row">
		<div class="col-md-2 col-md-offset-5">
			<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-warning btn-block text-center"%>
		</div>
	</div>
<% end %>

<h2 class="text-center"> My Events </h2>

	<% @posts.sort! {|x, y| y.start_date <=> x.start_date} %>
	<table class="col-md-12 table-striped" id="events">
		<thead>
			<tr>
				<th class="text-center"> Start Date</th>
				<th class="text-center"> Location </th>
				<th class="text-center"> Examine </th>
			</tr>
		</thead>
	<tbody>
		<% @posts.each do |post| %>
			<tr>
				<td class="text-center"> <%= post.start_date %> </td>
				<td class="text-center"> <%= post.location %> </td>
				<td class="text-center"> <%= link_to 'View', post_path(post) %> </td>
			</tr>
		<% end %>
	</tbody>
	</table>
</div>