config/routes.rb
Travlr::Application.routes.draw do

  resources :recommenders, only: [:create, :update, :destroy]
  resources :messages

  root 'home#welcome'
  get "prefs" => 'user_prefs#index'
  get "home/welcome" => 'home#welcome', as: :welcome
  get "home/login" => 'home#login', as: :login
  get "home/logout" => 'home#logout', as: :logout
  post "home/login" => 'home#authenticate', as: :authenticate  
  get 'inbox' => 'inbox#index', as: :inbox
  get 'recommend' => 'recommenders#recommend', as: :recommendation

  resources :users, except: :index
  resources :posts
  

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :location, presence: true
	validates :description, presence: true

	belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate

  # GET /posts
  # GET /posts.json
  def index
    @posts = Rails.cache.read("all_posts")
    unless @posts
      @posts = Post.all
      Rails.cache.write("all_posts", @posts)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post[:user_id] = session[:user_id]

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:start_date, :end_date, :location, :description)
    end

    def authenticate
      unless session[:user_id]
        flash[:notice] = "You must be logged in to view this page"
        redirect_to login_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_newpost.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Start Date: <%= f.date_select :start_date %>
  </div>
  <div class="field">
    End Date: <%= f.date_select :end_date %>
  </div>
  <div class="field">
    Location: <%= f.text_field :location %>
  </div>
  <div class="field">
    Description: <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'newpost' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1 class="text-center">All Posts</h1>

<table class="col-md-12 table-striped" id="posts">
  <thead>
      <tr>
        <th class="text-center"> Start Date</h3>
        <th class="text-center"> End Date</h3>
        <th class="text-center"> Location</h3>
        <th class="text-center"> Actions </h3>
      </tr>
  </thead>
<tbody>
  <% @posts.each do |post| %>
    <tr>
      <td class="text-center"> <%= post.start_date %> </td>
      <td class="text-center"> <%= post.end_date %> </td>
      <td class="text-center"> <%= post.location %> </td>
      <td class="text-center"> <%= link_to 'More Info', post, class: "btn btn-primary btn-xs" %> </td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'newpost' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start Date:</strong>
  <%= @post.start_date %>
</p>

<p>
  <strong>End Date:</strong>
  <%= @post.end_date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @post.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Created By: </strong>
  <%= User.find(@post.user_id).user_name %>
</p>

<%= link_to "Contact Organizer", new_message_path(user_name: User.find(@post.user_id).user_name), class: "btn btn-success" %>

<%= link_to 'Back', posts_path, class: "btn btn-primary" %>

<% if session[:user_id] == @post.user_id %>
	<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning" %>
<% end %>