config/routes.rb
Travlr::Application.routes.draw do

  resources :recommenders, only: [:create, :update, :destroy]
  resources :messages

  root 'home#welcome'
  get "prefs" => 'user_prefs#index'
  get "home/welcome" => 'home#welcome', as: :welcome
  get "home/login" => 'home#login', as: :login
  get "home/logout" => 'home#logout', as: :logout
  post "home/login" => 'home#authenticate', as: :authenticate  
  get 'inbox' => 'inbox#index', as: :inbox
  get 'recommend' => 'recommenders#recommend', as: :recommendation

  resources :users, except: :index
  resources :posts
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Travlr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'The Travlr', posts_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', posts_path %></li>
        <li><%= link_to 'New Post', new_post_path %></li>
        <li><%= link_to 'New Message', new_message_path %></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Inbox', inbox_path %></li>
        <li><%= link_to 'My Account', user_path(session[:user_id]) %></li>
        <li><%= link_to 'Logout', logout_path %><li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

	<div class="container">
		<%= yield %>
	</div>
</body>
</html>